export default class Tree {
    constructor(selector: any, ops: any);
    $el: HTMLElement;
    interpolate: RegExp;
    _data: any;
    nodes: any[];
    itemHeight: any;
    showCount: any;
    maxHeight: any;
    minHeight: any;
    data: any[];
    keyword: string;
    searchFilter: any;
    ready: any;
    $$breadcrumb: Breadcrumb | undefined;
    store: TreeStore;
    _init(): void;
    vlist: Vlist | undefined;
    _render(update?: boolean): void;
    _keywordFilter(data: any): void;
    _hasKeyword(v: any): any;
    _checkFilter(v: any): any;
    filter(keyword: string | undefined, onlySearchLeaf: any): any[];
    getNodeById(id: any): any;
    getCheckedNodes(...args: any[]): any[];
    setMaxValue(value?: number): void;
    scrollToIndex(index?: number): void;
    clearCheckedNodes(): void;
}
import Breadcrumb from "../breadcrumb";
import TreeStore from "./store";
import Vlist from "../virtual-list";
