/* Automatically generated by './build/bin/build-entry.js' */

import Checkbox from '../packages/checkbox/index.js';
import Breadcrumb from '../packages/breadcrumb/index.js';
import BreadcrumbItem from '../packages/breadcrumb-item/index.js';
import Tree from '../packages/tree/index.js';
import CollapseTransition from 'vs-tree/src/transitions/collapse-transition';

const components = [
  Checkbox,
  Breadcrumb,
  BreadcrumbItem,
  Tree,
  CollapseTransition
];

const install = function(Vue, opts = {}) {

  components.forEach(component => {
    Vue.component(component.name, component);
  });

  Vue.prototype.$KUI = {
    size: opts.size || '',
    zIndex: opts.zIndex || 2000
  };
};

/* istanbul ignore if */
if (typeof window !== 'undefined' && window.Vue) {
  install(window.Vue);
}

export default {
  version: require('../package.json').version,
  install,
  CollapseTransition,
  Checkbox,
  Breadcrumb,
  BreadcrumbItem,
  Tree
};
